import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header/header';
import { inter } from './fonts';
import clsx from 'clsx';
import { Footer } from '@/components/footer/footer';
import { AuthHeaderWrapper } from '@/components/auth-header-wrapperr/auth-header-wrapper';
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className)}>
        <AuthHeaderWrapper />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
